# Generated by Django 4.2.5 on 2024-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vesperrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
